services:
  mysql-db:
    image: mysql:8.0
    container_name: quantum-wallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quantum_wallet_db 
      MYSQL_USER: quantum_user
      MYSQL_PASSWORD: quantum_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wallet-network

  transaction-service:
    build:
      context: ../../backend/transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/quantum_wallet_db?createDatabaseIfNotExist=true&serverTimezone=UTC" # 🆕 Equalizado aqui também
      SPRING_DATASOURCE_USERNAME: "quantum_user"
      SPRING_DATASOURCE_PASSWORD: "quantum_password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - mysql-db
    networks:
      - wallet-network

volumes:
  mysql_data:

networks:
  wallet-network:
    driver: bridge